apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-kv
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://kv-devagent-01.vault.azure.net/"
      tenantId: "8451e4fe-59c7-46a5-9810-ae5b17852ea4"
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
